function [E] = read_cosmo_input_file(filename) 

  f = fopen(filename, 'r');
    
    
%        [sampleid, name, email, lat, long, ...
%         be_conc, al_conc, c_conc, ne_conc, ...
%         be_uncer, al_uncer, c_uncer, ne_uncer, ...
%         be_prod, al_prod, c_prod, ne_prod, ...
%         rock_density, ...
%         epsilon_gla_min, epsilon_gla_max, ...
%         epsilon_int_min, epsilon_int_max, ...
%         t_degla, t_degla_uncer, ...
%         d18O_smoothing, ...
%         d18O_threshold_min, d18O_threshold_max]
    C = textscan(f, strcat(...
        '%s %s %s %s %s ', ...
        '%s %s %s %s ', ...
        '%s %s %s %s ', ...
        '%s ', ...
        '%s %s ', ...
        '%s %s ', ...
        '%s %s ', ...
        '%s ', ...
        '%s %s '));
    
    % read values sequentially
%     sampleid = fscanf(f, '%s');
%     name     = fscanf(f, '%s\t');
%     email    = fscanf(f, '%s\t');
%     lat      = fscanf(f, '%s\t');
%     long     = fscanf(f, '%s\t');
    

        
   % fclose(f);

    keyboard
    
end